### ISSUE TITLE
auto respawn when fall

### ISSUE THREAD

**Issue by goinsidevr** [vrlandio/community#237]
whenever I fall from the main surface of a room I would like to respawn automatically before I reach the floor

**Comment by arpu** [comment]
how should we define the main surface?

**Comment by goinsidevr** [comment]
individually but only for some projects. idk how to do it automatically

**Comment by arpu** [comment]
not a simple task, a user can always simple re spawn with the key r on desktop for now

**Comment by goinsidevr** [comment]
very important to find an easy workaround for this event because it destroys the intended artistic expression, immersion and emotion

**Comment by arpu** [comment]
ok, need to think more on this first idea is to add a Server/space global option for admins to set 
a Room Size on y Axes and all under this value the user gets respawn

**Comment by goinsidevr** [comment]
Great idea! I`m only wondering whether this applies to sphere shaped Rooms as well? Would definitely help anyway.

**Comment by arpu** [comment]
fixed with v0.25.7 in Space nPLTeE/GOinsideVR_OALA automatic respawn at player height 100

**Comment by goinsidevr** [comment]
yess! works great, thx!

**Comment by goinsidevr** [comment]
ohh no! it doesnt work anymore. tried everything. changed position, reloaded several times, emtied cache, logged in again. first few times it worked great

**Comment by arpu** [comment]
copy i understand the problem now, after you set the spawn Point again the autoSpawnPoint was deleted in the database 
( this will be fixed with a new autospawnPoint gui in the server Settings)

**Comment by goinsidevr** [comment]
alright! glad you found it.

**Comment by goinsidevr** [comment]
while in vr mode you cant easily reload. you feel completely stuck

**Comment by arpu** [comment]
its enabled again in the Anny Room

**Comment by arpu** [comment]
option is available in the Server/space Settings
