### ISSUE TITLE
how to kick out trolls?

### ISSUE THREAD

**Issue by goinsidevr** [vrlandio/community#239]
can I somehow kick out people trolling?

**Comment by arpu** [comment]
kick/ban is implemented on server side but not exposed on GUI, needs proper gui design in chat widget for room admins

**Comment by goinsidevr** [comment]
we have the situation now of one person still being online in our room without noticing. there's no need to completely kick this person out but at least mute the mic would be needed otherwise it would disturb our next show.

**Comment by goinsidevr** [comment]
any updates on this one?

**Comment by arpu** [comment]
fixed in v0.26.3

Thanks!
